module MotionBundler
  FILES = [
    "/Users/johngallagher/Dropbox/Projects/ProgrammingProjects/CurrentProjects/lapsus/.motion-bundler.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/motion-bundler-0.2.1/lib/motion-bundler/device/boot.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/motion-bundler-0.2.1/lib/motion-bundler/device/core_ext.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-1.7.1/motion/shortcut.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-1.7.1/lib/bubble-wrap/version.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-1.7.1/motion/util/deprecated.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-1.7.1/motion/reactor.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-1.7.1/motion/reactor/default_deferrable.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-1.7.1/motion/reactor/deferrable.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-1.7.1/motion/reactor/eventable.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-1.7.1/motion/reactor/future.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-1.7.1/motion/reactor/periodic_timer.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-1.7.1/motion/reactor/queue.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-1.7.1/motion/reactor/timer.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-1.7.1/motion/core.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-1.7.1/motion/core/app.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-1.7.1/motion/core/device.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-1.7.1/motion/core/json.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-1.7.1/motion/core/kvo.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-1.7.1/motion/core/ns_index_path.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-1.7.1/motion/core/ns_notification_center.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-1.7.1/motion/core/ns_url_request.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-1.7.1/motion/core/ns_user_defaults.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-1.7.1/motion/core/persistence.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-1.7.1/motion/core/pollute.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-1.7.1/motion/core/string.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-1.7.1/motion/core/time.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-1.7.1/motion/core/device/screen.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-1.7.1/motion/core/osx/app.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-1.7.1/motion/core/osx/device.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-1.7.1/motion/core/device/osx/screen.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-http-1.7.1/motion/http/query.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-http-1.7.1/motion/http/response.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/bubble-wrap-http-1.7.1/motion/http.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/cdq-0.1.11/motion/cdq.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/cdq-0.1.11/motion/managed_object.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/cdq-0.1.11/motion/cdq/collection_proxy.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/cdq-0.1.11/motion/cdq/config.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/cdq-0.1.11/motion/cdq/context.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/cdq-0.1.11/motion/cdq/model.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/cdq-0.1.11/motion/cdq/object.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/cdq-0.1.11/motion/cdq/object_proxy.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/cdq-0.1.11/motion/cdq/partial_predicate.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/cdq-0.1.11/motion/cdq/query.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/cdq-0.1.11/motion/cdq/relationship_query.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/cdq-0.1.11/motion/cdq/store.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/cdq-0.1.11/motion/cdq/targeted_query.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/motion-yaml-1.4/lib/project/yaml.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/motion-redgreen-1.0.0/lib/motion-redgreen/ansiterm.rb",
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/motion-redgreen-1.0.0/lib/motion-redgreen/string.rb",
    "/Users/johngallagher/Dropbox/Projects/ProgrammingProjects/CurrentProjects/lapsus/mocks/ostruct.rb",
    "/Users/johngallagher/Dropbox/Projects/ProgrammingProjects/CurrentProjects/lapsus/mocks/pathname.rb",
    "/Users/johngallagher/Dropbox/Projects/ProgrammingProjects/CurrentProjects/lapsus/mocks/time.rb",
    "/Users/johngallagher/Dropbox/Projects/ProgrammingProjects/CurrentProjects/lapsus/mocks/date/format.rb",
    "/Users/johngallagher/Dropbox/Projects/ProgrammingProjects/CurrentProjects/lapsus/app/app_delegate.rb",
    "/Users/johngallagher/Dropbox/Projects/ProgrammingProjects/CurrentProjects/lapsus/app/models/entry.rb",
    "/Users/johngallagher/Dropbox/Projects/ProgrammingProjects/CurrentProjects/lapsus/lib/models/entry_dummy.rb",
    "/Users/johngallagher/Dropbox/Projects/ProgrammingProjects/CurrentProjects/lapsus/lib/models/entry_mixin.rb"
  ]
  FILES_DEPENDENCIES = {
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/motion-bundler-0.2.1/lib/motion-bundler/device/boot.rb" => [
      "/Users/johngallagher/.gem/ruby/2.2.0/gems/motion-bundler-0.2.1/lib/motion-bundler/device/core_ext.rb"
    ],
    "/Users/johngallagher/Dropbox/Projects/ProgrammingProjects/CurrentProjects/lapsus/mocks/time.rb" => [
      "/Users/johngallagher/Dropbox/Projects/ProgrammingProjects/CurrentProjects/lapsus/mocks/date/format.rb"
    ]
  }
  REQUIRES = [
    "/Users/johngallagher/.gem/ruby/2.2.0/gems/motion-bundler-0.2.1/lib/motion-bundler/device/boot.rb",
    "/Users/johngallagher/Dropbox/Projects/ProgrammingProjects/CurrentProjects/lapsus/.motion-bundler.rb",
    "core_ext",
    "date/format",
    "ostruct",
    "pathname",
    "time"
  ]
end
