// Generated by IB v0.7.2 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation MainWindowController
@end

@implementation MinutesDurationFormatter
@end

@implementation ProjectSummaryController
@end

@implementation SourceListController
@end

