// Generated by IB v0.7.2 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <AppKit/AppKit.h>
#import <ApplicationServices/ApplicationServices.h>
#import <CoreData/CoreData.h>
#import <CoreGraphics/CoreGraphics.h>
#import <CoreServices/CoreServices.h>
#import <Foundation/Foundation.h>

@interface MainWindowController: NSWindowController

@property IBOutlet id source_list_controller;
@property IBOutlet id project_summary_controller;

@end

@interface MinutesDurationFormatter: NSFormatter
-(IBAction) stringForObjectValue:(id) seconds;

@end

@interface ProjectSummaryController: NSViewController

@property IBOutlet NSSegmentedCell * range_selector;
@property IBOutlet NSDatePicker * date_selector;
@property IBOutlet NSTableView * table_view;

-(IBAction) awakeFromNib;
-(IBAction) select_today;
-(IBAction) select_date:(id) sender;
-(IBAction) change_date_to:(id) selected_date;
-(IBAction) numberOfRowsInTableView:(id) tableView;

@end

@interface SourceListController: NSViewController

@property IBOutlet NSOutlineView * outline_view;
@property IBOutlet NSTableView * table_view;

-(IBAction) add:(id) sender;
-(IBAction) remove:(id) sender;
-(IBAction) reload;
-(IBAction) awakeFromNib;

@end

