// Generated by IB v0.7.2 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <AppKit/AppKit.h>
#import <ApplicationServices/ApplicationServices.h>
#import <CoreData/CoreData.h>
#import <CoreGraphics/CoreGraphics.h>
#import <CoreServices/CoreServices.h>
#import <Foundation/Foundation.h>

@interface MainWindowController: NSWindowController
-(IBAction) add:(id) sender;
-(IBAction) remove:(id) sender;

@end

@interface ProjectSummaryController: NSViewController

@property IBOutlet NSSegmentedCell * range_selector;
@property IBOutlet NSDatePicker * date_selector;
@property IBOutlet NSTableView * table_view;

-(IBAction) awakeFromNib;
-(IBAction) select_date:(id) sender;
-(IBAction) numberOfRowsInTableView:(id) tableView;

@end

@interface SourceListController: NSViewController

@property IBOutlet NSArrayController * entries_controller;

-(IBAction) add:(id) sender;
-(IBAction) remove:(id) sender;
-(IBAction) awakeFromNib;
-(IBAction) outlineViewSelectionDidChange:(id) notification;

@end

