// Generated by IB v0.7.2 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <AppKit/AppKit.h>
#import <ApplicationServices/ApplicationServices.h>
#import <CoreData/CoreData.h>
#import <CoreGraphics/CoreGraphics.h>
#import <CoreServices/CoreServices.h>
#import <Foundation/Foundation.h>

@interface MainWindowController: NSWindowController
-(IBAction) add:(id) sender;
-(IBAction) remove:(id) sender;

@end

@interface ProjectSummaryController: NSViewController

@property IBOutlet NSOutlineView * source_list;

@end

@interface SourceListController: NSViewController
-(IBAction) add:(id) sender;
-(IBAction) remove:(id) sender;

@end

